### PR TITLE
fixed opengl example

### PR DESCRIPTION
**Pull request by CodeDoes**

### CODE REVIEW

**Comment by Vladar4** [comment]
Opengl v1.1.0, which is installed with `nimble install opengl` command, don't yet has separate `opengl` directory.

Do you have some special reason to use `opengl@#head` in this example? Otherwise I'd rather stay with the stable version for now.

**Comment by CodeDoes** [comment]
Yes. opengl stable doesn't work with develop. I can make it conditional to the nimversion if that would be better. Or we can leave this commit until the next nim version which should be at the end of the month.

**Comment by Vladar4** [comment]
The latter option looks preferable, considering there might be some other adjustments with the new Nim release.

**Comment by Vladar4** [comment]
> glad

Well, for a serious project it might be beneficial. But for a basic binding example I wouldn't want to confuse anyone with something more than a necessary minimum.

**Pull request merged**
