### PR TITLE
Made SDL_gpu wrapper reflect recent changes

### PR DESCRIPTION
**Pull request by Serenitor**

### CODE REVIEW

**Comment by Serenitor** [comment]
Also just removed hasMusicDecoder from the sdl_mixer.nim.

With that import, my binaries crashed with:
```
could not import: Mix_HasMusicDecoder
The terminal process terminated with exit code: 1
```
while using the up to date SDL_mixer 2.0.2

I then downloaded the source of SDL_mixer and found out that `hasMusicDecoder` is merely declared but not defined. I guess it's an remnant of some sort or not yet implemented? Anyways it should be save to remove.

**Comment by Vladar4** [comment]
> I then downloaded the source of SDL_mixer and found out that hasMusicDecoder is merely declared but not defined. I guess it's an remnant of some sort or not yet implemented? Anyways it should be save to remove.

Could you please comment this proc out and add appropriate commentary instead? This proc was added in the latest release so it might still be implemented in the future.

P.S.: I'd recommend to separate unrelated pull requests from each other in the future, for ease of management.

**Comment by Serenitor** [comment]
Done.

Still have to figure some of the git stuff out. I can separate pull requests by using individual branches for commits, is that right?

**Comment by Vladar4** [comment]
Thanks!

> I can separate pull requests by using individual branches for commits, is that right?

Correct. More info [here](https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/).

**Pull request merged**
